services:
  postgres:
    image: postgres:17.2
    environment:
      POSTGRES_DB: "auth_db"
      POSTGRES_USER: "rissochek"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ruslanynysov@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "8080:80"
    depends_on:
      - postgres
